"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const nome = "Otavio";
const idade = 18;
const matriculado = true;
const cidade = "Araras";
console.log(nome);
console.log(idade);
console.log(matriculado);
console.log(cidade);
